#!/usr/bin/env python
# -*- coding:utf-8 -*-


# ############################################################################
#  license :
# ============================================================================
#
#  File :        BottomServer.py
#
#  Project :     
#
# This file is part of Tango device class.
# 
# Tango is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Tango is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Tango.  If not, see <http://www.gnu.org/licenses/>.
# 
#
#  $Author :      michael.hellmig$
#
#  $Revision :    $
#
#  $Date :        $
#
#  $HeadUrl :     $
# ============================================================================
#            This file is generated by POGO
#     (Program Obviously used to Generate tango Object)
# ############################################################################

__all__ = ["BottomServer", "BottomServerClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
# Add additional import
#----- PROTECTED REGION ID(BottomServer.additionnal_import) ENABLED START -----#
from bladesctrl import TopCtrl
#----- PROTECTED REGION END -----#	//	BottomServer.additionnal_import

# Device States Description
# No states for this device


class BottomServer (PyTango.Device_4Impl):
    """"""
    
    # -------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(BottomServer.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	BottomServer.global_variables

    def __init__(self, cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        BottomServer.init_device(self)
        #----- PROTECTED REGION ID(BottomServer.__init__) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	BottomServer.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(BottomServer.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	BottomServer.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_Position_read = 0.0
        #----- PROTECTED REGION ID(BottomServer.init_device) ENABLED START -----#
        socket_host = self.GetHostname()
        socket_port = self.GetPort()
        self.topCtrl = TopCtrl(socket_host, socket_port)
        #----- PROTECTED REGION END -----#	//	BottomServer.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(BottomServer.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	BottomServer.always_executed_hook

    # -------------------------------------------------------------------------
    #    BottomServer read/write attribute methods
    # -------------------------------------------------------------------------
    
    def read_Position(self, attr):
        self.debug_stream("In read_Position()")
        #----- PROTECTED REGION ID(BottomServer.Position_read) ENABLED START -----#
        topCtrl = self.topCtrl      
        ans = topCtrl.get_position()   
        attr.set_value(ans)
        #----- PROTECTED REGION END -----#	//	BottomServer.Position_read
        
    
    
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(BottomServer.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	BottomServer.read_attr_hardware


    # -------------------------------------------------------------------------
    #    BottomServer command methods
    # -------------------------------------------------------------------------
    
    def dev_state(self):
        """ This command gets the device state (stored in its device_state data member) and returns it to the caller.
        :return: Device state
        :rtype: PyTango.CmdArgType.DevState
        """
        self.debug_stream("In dev_state()")
        argout = PyTango.DevState.UNKNOWN
        #----- PROTECTED REGION ID(BottomServer.State) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	BottomServer.State
        if argout != PyTango.DevState.ALARM:
            PyTango.Device_4Impl.dev_state(self)
        return self.get_state()
        
    def dev_status(self):
        """ This command gets the device status (stored in its device_status data member) and returns it to the caller.
        :return: Device status
        :rtype: PyTango.ConstDevString
        """
        self.debug_stream("In dev_status()")
        argout = ""
        #----- PROTECTED REGION ID(BottomServer.Status) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	BottomServer.Status
        self.set_status(self.argout)
        self.__status = PyTango.Device_4Impl.dev_status(self)
        return self.__status
        
    def MoveTop40(self):
        """ 
        :rtype: PyTango.DevBoolean
        """
        self.debug_stream("In MoveTop40()")
        argout = False
        #----- PROTECTED REGION ID(BottomServer.MoveTop40) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	BottomServer.MoveTop40
        return argout
        
    def StopMotor(self, argin):
        """ 
        :param argin: 
        :type argin: PyTango.DevString
        :rtype: PyTango.DevBoolean
        """
        self.debug_stream("In StopMotor()")
        argout = False
        #----- PROTECTED REGION ID(BottomServer.StopMotor) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	BottomServer.StopMotor
        return argout
        
    def GetHostname(self):
        """ 
        :rtype: PyTango.DevString
        """
        self.debug_stream("In GetHostname()")
        argout = ""
        #----- PROTECTED REGION ID(BottomServer.GetHostname) ENABLED START -----#
        dev = PyTango.DeviceProxy('s/hhl/2')
        s = dev.get_property('hostname')
        m = s['hostname']  
        argout = m[0]
        #----- PROTECTED REGION END -----#	//	BottomServer.GetHostname
        return argout
        
    def GetPort(self):
        """ 
        :rtype: PyTango.DevLong
        """
        self.debug_stream("In GetPort()")
        argout = 0
        #----- PROTECTED REGION ID(BottomServer.GetPort) ENABLED START -----#
        dev = PyTango.DeviceProxy('s/hhl/2')
        s = dev.get_property('port')
        m = s['port']  
        argout = int(m[0])
      
        #----- PROTECTED REGION END -----#	//	BottomServer.GetPort
        return argout
        
    def SetPosition(self, argin):
        """ 
        :param argin: 
        :type argin: PyTango.DevDouble
        :rtype: PyTango.DevBoolean
        """
        self.debug_stream("In SetPosition()")
        argout = False
        #----- PROTECTED REGION ID(BottomServer.SetPosition) ENABLED START -----#
        topCtrl= self.topCtrl
        topCtrl.moveMotor(argin)
        argout = True
        #----- PROTECTED REGION END -----#	//	BottomServer.SetPosition
        return argout
        
    def GetPosition(self):
        """ 
        :rtype: PyTango.DevDouble
        """
        self.debug_stream("In GetPosition()")
        argout = 0.0
        #----- PROTECTED REGION ID(BottomServer.GetPosition) ENABLED START -----#
        topCtrl= self.topCtrl
        argout=topCtrl.get_position()
        #----- PROTECTED REGION END -----#	//	BottomServer.GetPosition
        return argout
        

    #----- PROTECTED REGION ID(BottomServer.programmer_methods) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	BottomServer.programmer_methods

class BottomServerClass(PyTango.DeviceClass):
    # -------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(BottomServer.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	BottomServer.global_class_variables


    #    Class Properties
    class_property_list = {
        'Socket':
            [PyTango.DevString, 
             '',
            [] ],
        }


    #    Device Properties
    device_property_list = {
        'id':
            [PyTango.DevDouble, 
             '',
            [1]],
        }


    #    Command definitions
    cmd_list = {
        'MoveTop40':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevBoolean, "none"]],
        'StopMotor':
            [[PyTango.DevString, "none"],
            [PyTango.DevBoolean, "none"]],
        'GetHostname':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevString, "none"]],
        'GetPort':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevLong, "none"]],
        'SetPosition':
            [[PyTango.DevDouble, "none"],
            [PyTango.DevBoolean, "none"]],
        'GetPosition':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevDouble, "none"]],
        }


    #    Attribute definitions
    attr_list = {
        'Position':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(BottomServerClass, BottomServer, 'BottomServer')
        #----- PROTECTED REGION ID(BottomServer.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	BottomServer.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed as e:
        print ('-------> Received a DevFailed exception:', e)
    except Exception as e:
        print ('-------> An unforeseen exception occured....', e)

if __name__ == '__main__':
    main()
