#!/usr/bin/env python
# -*- coding:utf-8 -*-


# ############################################################################
#  license :
# ============================================================================
#
#  File :        HhlServer.py
#
#  Project :     
#
# This file is part of Tango device class.
# 
# Tango is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Tango is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Tango.  If not, see <http://www.gnu.org/licenses/>.
# 
#
#  $Author :      huiling.he$
#
#  $Revision :    $
#
#  $Date :        $
#
#  $HeadUrl :     $
# ============================================================================
#            This file is generated by POGO
#     (Program Obviously used to Generate tango Object)
# ############################################################################

__all__ = ["HhlServer", "HhlServerClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
# Add additional import
#----- PROTECTED REGION ID(HhlServer.additionnal_import) ENABLED START -----#
from socketAPI import BlenderBlades
#----- PROTECTED REGION END -----#	//	HhlServer.additionnal_import

# Device States Description
# No states for this device


class HhlServer (PyTango.Device_4Impl):
    """"""
    
    # -------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(HhlServer.global_variables) ENABLED START -----#
   
    #----- PROTECTED REGION END -----#	//	HhlServer.global_variables

    def __init__(self, cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        HhlServer.init_device(self)
        #----- PROTECTED REGION ID(HhlServer.__init__) ENABLED START -----#
        self.blender_blades = BlenderBlades('127.0.0.1', 9999)
        #----- PROTECTED REGION END -----#	//	HhlServer.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(HhlServer.delete_device) ENABLED START -----#
        del self.blender_blades
        #----- PROTECTED REGION END -----#	//	HhlServer.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_Position_read = 0.0
        #----- PROTECTED REGION ID(HhlServer.init_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	HhlServer.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(HhlServer.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	HhlServer.always_executed_hook

    # -------------------------------------------------------------------------
    #    HhlServer read/write attribute methods
    # -------------------------------------------------------------------------
    
    def read_Position(self, attr):
        self.debug_stream("In read_Position()")
        #----- PROTECTED REGION ID(HhlServer.Position_read) ENABLED START -----#
        #attr.set_value(self.attr_Position_read)
        blender_blades = self.blender_blades        
        ans = blender_blades.get_position(1)      
        attr.set_value(ans)
        #----- PROTECTED REGION END -----#	//	HhlServer.Position_read
        
    
    
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(HhlServer.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	HhlServer.read_attr_hardware


    # -------------------------------------------------------------------------
    #    HhlServer command methods
    # -------------------------------------------------------------------------
    
    def dev_state(self):
        """ This command gets the device state (stored in its device_state data member) and returns it to the caller.
        :return: Device state
        :rtype: PyTango.CmdArgType.DevState
        """
        self.debug_stream("In dev_state()")
        argout = PyTango.DevState.UNKNOWN
        #----- PROTECTED REGION ID(HhlServer.State) ENABLED START -----#
        blender_blades = self.blender_blades
        argout = blender_blades.get_state(1)
     
        if argout != PyTango.DevState.ALARM:
            PyTango.Device_4Impl.dev_state(self)
            argout = PyTango.DevState.ON
        return argout
  
        #----- PROTECTED REGION END -----#	//	HhlServer.State
        if argout != PyTango.DevState.ALARM:
            PyTango.Device_4Impl.dev_state(self)
        return self.get_state()
        
    def dev_status(self):
        """ This command gets the device status (stored in its device_status data member) and returns it to the caller.
        :return: Device status
        :rtype: PyTango.ConstDevString
        """
        self.debug_stream("In dev_status()")
        argout = ""
        #----- PROTECTED REGION ID(HhlServer.Status) ENABLED START -----#
        blender_blades = self.blender_blades
        ans = blender_blades.ask("?states")
        state_raw = ans.split()[0]
        if argout != state_raw:
            argout='Status ON'
        return argout
        #----- PROTECTED REGION END -----#	//	HhlServer.Status
        self.set_status(self.argout)
        self.__status = PyTango.Device_4Impl.dev_status(self)
        return self.__status
        
    def Move(self, argin):
        """ 
        :param argin: 
        :type argin: PyTango.DevFloat
        :rtype: PyTango.DevBoolean
        """
        self.debug_stream("In Move()")
        argout = False
        #----- PROTECTED REGION ID(HhlServer.Move) ENABLED START -----#
        blender_blades = self.blender_blades
        ans = blender_blades.moveMotor(1, argin)
        if ans != None:
            argout = True
        #----- PROTECTED REGION END -----#	//	HhlServer.Move
        return argout
        
    def Stop(self):
        """ 
        """
        self.debug_stream("In Stop()")
        #----- PROTECTED REGION ID(HhlServer.Stop) ENABLED START -----#
        blender_blades = self.blender_blades
        blender_blades.stop(1)
        
        #----- PROTECTED REGION END -----#	//	HhlServer.Stop
        
    def GetAcceleration(self):
        """ 
        :rtype: PyTango.DevFloat
        """
        self.debug_stream("In GetAcceleration()")
        argout = 0.0
        #----- PROTECTED REGION ID(HhlServer.GetAcceleration) ENABLED START -----#
        blender_blades = self.blender_blades
        v = blender_blades.GetAxisPar(1, "acceleration")
    
        if argout != v:
            argout = v
        #----- PROTECTED REGION END -----#	//	HhlServer.GetAcceleration
        return argout
        
    def SetAcceleration(self, argin):
        """ 
        :param argin: 
        :type argin: PyTango.DevFloat
        :rtype: PyTango.DevString
        """
        self.debug_stream("In SetAcceleration()")
        argout = ""
        #----- PROTECTED REGION ID(HhlServer.SetAcceleration) ENABLED START -----#
        blender_blades = self.blender_blades
        ans = blender_blades.SetAxisPar(1,"acceleration", argin)
        #----- PROTECTED REGION END -----#	//	HhlServer.SetAcceleration     
        return argout
        

    #----- PROTECTED REGION ID(HhlServer.programmer_methods) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	HhlServer.programmer_methods

class HhlServerClass(PyTango.DeviceClass):
    # -------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(HhlServer.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	HhlServer.global_class_variables


    #    Class Properties
    class_property_list = {
        'Socket':
            [PyTango.DevString, 
             '',
            [] ],
        }


    #    Device Properties
    device_property_list = {
        'id':
            [PyTango.DevShort, 
             '',
            [1]],
        }


    #    Command definitions
    cmd_list = {
        'Move':
            [[PyTango.DevFloat, "none"],
            [PyTango.DevBoolean, "none"]],
        'Stop':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'GetAcceleration':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevFloat, "none"]],
        'SetAcceleration':
            [[PyTango.DevFloat, "none"],
            [PyTango.DevString, "none"]],
        }


    #    Attribute definitions
    attr_list = {
        'Position':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(HhlServerClass, HhlServer, 'HhlServer')
        #----- PROTECTED REGION ID(HhlServer.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	HhlServer.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed as e:
        print ('-------> Received a DevFailed exception:', e)
    except Exception as e:
        print ('-------> An unforeseen exception occured....', e)

if __name__ == '__main__':
    main()
